[General]
user-agent = Locket/1.0.0 (iPhone; iOS 18; Scale/3.00)

[Script]

# This module for Shadowrocket - Enable Locket Gold feature, and it free!
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/Win98Plus/Shadowrocket_Module_Win98Plus/refs/heads/main/LocketGold.js, requires-body=true, max-size=-1, timeout=120
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts|subscribers), script-path=https://github.com/Win98Plus/Shadowrocket_Module_Win98Plus/blob/main/deleteHeader.js, timeout=120

[MITM]
hostname = api.revenuecat.com, raw.githubusercontent.com
